- name: Intro to Ansible Playbooks
  hosts: all

  tasks:
  - name: Upgrade all apt packages
    apt:
      force_apt_get: yes
      upgrade: dist
      cache_valid_time: 86400 #One day
    become: yes


